### ISSUE TITLE
No search capabilities when using in ModelAdmin

### ISSUE THREAD

**Issue by nimeso** [UndefinedOffset/SortableGridField#108]
Currently in the docs example it removes Silverstripes default search/filter stuff. Is there a way to keep this?

**Comment by UndefinedOffset** [comment]
In the 3.x releases of SilverStripe the search/filter is always removed in model admin? It gets moved to the search icon at the top of the screen beside the tabs, this is normal behavior of model admin and isn't caused by sortable GridField I do turn them off when drag-n-drop sorting is on in a normal GridField but that is to keep the sortable headers from breaking the drag-n-drop sorting.

**Comment by nimeso** [comment]
OMG! duh. Been awhile since I used SS. Cheers heaps

**Comment by UndefinedOffset** [comment]
No worries ;)
