### ISSUE TITLE
Improved UI for moving to another page

### ISSUE THREAD

**Issue by UndefinedOffset** [UndefinedOffset/SortableGridField#72]
Should come up with a better UI for moving rows to another page, right now the pagination arrows are used but its not that obvious what is going on. Maybe larger arrows with text labels on the edges of the grid field something like that?

**Comment by 4t4r1** [comment]
Possibly also drag-&-droppable page numbers - if it's not too much of a mission :)

Could also have hover titles when dragging e.g. "send `DataObject` to page 3"

**Comment by UndefinedOffset** [comment]
Ya I like the idea of that, maybe have the text labels be "send {singular name} to page #"

**Comment by sum-github** [comment]
Desperately needed this functionality as I am struggling to move the objects in between pages when dealing with 150 pictures on different pages.

**Comment by 4t4r1** [comment]
So, a couple of thoughts here:

Firstly, it may be worth mentioning in the README that people can de-paginate the list. I remember using this as a programmatic solution (obviously, if the situation allows), rather than having to explain it over & over again to clients. I asked the question of how to de-paginate GridField [here](http://stackoverflow.com/questions/19637540/silverstripe-3-1-remove-sortablegridfield-pagnation-and-show-all-dataobejcts) once upon a time.

*Wishlist*
CMS users being able to toggle pagination on/off in the GridField pagination area if SortableGF is active - could perhaps solve 99% of the issues?

Also, I think the issues here is mostly UX-related. Could be worth spending some time getting a good UX spread & implementing some extended CSS & JS to improve the interface. Happy to help, although I have successfully managed to safely steer clear of CMS's Entwine for 6 years now *sigh* it was never gonna last :P

**Comment by sum-github** [comment]
I agree the ability to toggle pagination on and off in the GridField pagination area will solve all the issues. Similar sort of mechanism as it was version 2.4.

Do you know whether the functionality to move the objects onto mulitple pages exists or not in GridField?

<a href="http://www.silverstripe.org/community/forums/all-other-modules/show/102580">See my post here.</a>

**Comment by UndefinedOffset** [comment]
@sum-github right now currently the only way to do this is to drag over the pagination arrows, this issue is primarily about improving the UI/UX to make it more friendly and easier to do.

**Comment by UndefinedOffset** [comment]
@4t4r1 At one time (long ago) SortableGridField automatically depaginated the gridfield when you toggled the sorting. But Ingo aka chillu warned me against this since pagination does help when with resources when you have a very long list of objects to display. So I came up with the current solution. I know there is a module out there that does provide a button allowing the user to disable the pagination, I'm blanking at the moment though. I'll add it as a suggested module in composer when I build out the new solution for pagination.

**Comment by UndefinedOffset** [comment]
I suppose I could also add a checkbox to do that too...

**Comment by 4t4r1** [comment]
Rushing headlong through space the creature could feel stray molecules kiss it's broad vacuum wings as it streched them wide. Scintillations from the tenuous impact dripped from it's trailing edge... err... wait... I was somewhere else.

Yes & no, generally if you click that button, you know what you're in for... :)

**Comment by UndefinedOffset** [comment]
So this is what I'm thinking of doing, when you start dragging the arrow/bar on the right would appear to move the item to the next page. There would also be on on the left if you are in a middle page. It gets darker/more visible when you drag over it.

![silverstripe_-_edit_page_-_2015-08-29_15 07 55](https://cloud.githubusercontent.com/assets/1391558/9563625/d729ceaa-4e5f-11e5-985a-c8484ead3509.png)

**Comment by UndefinedOffset** [comment]
This is the module btw that has the show all support [normann/gridfieldpaginatorwithshowall](https://github.com/normann/gridfieldpaginatorwithshowall)

**Comment by UndefinedOffset** [comment]
Hey guys, I've just committed a change to the [new-page-sort](https://github.com/UndefinedOffset/SortableGridField/tree/new-page-sort) branch you guys mind giving it a try I'm curious what your thoughts are.

**Comment by UndefinedOffset** [comment]
this has been merged to master and will be included in the 0.5.0 tag shortly
