### ISSUE TITLE
Issue edit and Adding New Gallery Holder Page and Gallery Page

### ISSUE THREAD

**Issue by stefanok** [UndefinedOffset/SortableGridField#89]
Hi guys,

The first issue is that i cant seem to add or edit existing gallery pages. When i try and do this i get this error: Error at line 145 of /public_html/sortablegridfield/code/forms/GridFieldSortableRows.php

When i look at that line it is as follows: 
				if(is_array($fieldType)) {
					user_error('Sort column '.$this->sortColumn.' could not be found in '.$gridField->getModelClass().'\'s ancestry', E_USER_ERROR);
				}else {
					user_error('Sort column '.$this->sortColumn.' must be an Int, column is of type '.$fieldType, E_USER_ERROR);
				}

2nd Issue and it is linked. On the front end, if i click on an image in the agllery i get this:
The light box opens and says this inside - Action 'photos' isn't allowed on class GalleryPage_Controller.

Any help would be appreciated, i am a noob.

**Comment by UndefinedOffset** [comment]
Lets start with the first question/issue, the two errors that you copied here mean one of two things. The first one means it couldn't find the sort column in on your related object, the second one means it's not of the type "Int". It appears you maybe using an old version because 145 is not that in the latest version in which case it could be simply that you need to define your sort column as an "Int" (case sensitive). I'm not sure which one you are seeing because those lines are not that in the latest version. Can you post some code snippets primarily how you are setting up the relationship that the gridfield is using? Something like [this](https://github.com/silverstripe/one-ring-rentals/blob/master/mysite/code/ArticlePage.php#L20-L27), if you are using a many_many relationship I'll need to see the definition of your many_many_extraFields.If you are using a has_many relationship i'll need to see the $db static on the related object.

As for your 2nd issue, you need to add "photos" to the $allowed_actions static on your GalleryPage_Controller something like [this](https://github.com/silverstripe/one-ring-rentals/blob/master/mysite/code/ArticlePage.php#L77-L79)

**Comment by stefanok** [comment]
Thank you so much for your reply!!! I really appreciate it!

This is what i did:
•	SortOrder field was missing in GalleryImage table
•	We have added it and GalleryPage_Controller was missing "photos" in allowed actions list

**Comment by UndefinedOffset** [comment]
Has that fixed the issue you were having?

**Comment by stefanok** [comment]
Yes it has - thank you so much!
